name: Cafe M3U Generator

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını indir
        uses: actions/checkout@v4

      - name: Python 3.10 kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Gerekli paketleri kur
        run: pip install requests

      - name: Python scripti çalıştır
        run: python sporcafe.py

      - name: Üretilen M3U dosyasını kaydet (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: cafe-m3u
          path: cafe.m3u
          compression-level: 0
