name: M3U Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: PHP script çalıştır
        run: php index.php

      - name: M3U var mı kontrol et
        run: ls -lh NETSpor.m3u

      - name: Artifact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: NETSpor
          path: NETSpor.m3u
