name: M3U Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: PHP kur
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: PHP script çalıştır
        run: php index.php

      - name: Dosyaları listele
        run: ls -lh

      - name: Debug göster
        run: cat debug.txt || true

      - name: Artifact yükle
        uses: actions/upload-artifact@v4
        with:
          name: netsport-debug
          path: |
            NETSpor.m3u
            debug.txt
