name: Update Metv

on:
  schedule:
    - cron: "*/15 * * * *"  # 15 dakikada bir
  workflow_dispatch:

permissions:
  contents: write  # Repo'ya push için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # <-- tüm geçmişi klonla (önemli!)

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run metv script
        run: python metv.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metv/
          git diff --cached --quiet || git commit -m "Update metv folder"
          
          # Uzak branch'teki değişiklikleri çek ve rebase et
          git pull origin main --rebase || true
          
          # Push işlemi (gerekirse force kullan)
          git push origin main || git push origin main --force
